### ISSUE TITLE
BC Model12 Simulation

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-dipoles-bc#1]
Added model for analysis:

 si-dipoles-bc/model-12/simulation/magnetic/2017-08-21_bc_model12_X=-90_12mm_Z=-1000_1000mm.txt

**Comment by xresende** [comment]
* integrated dipolar and quadrupolar fields are within spec. 
* sextupole, although smaller than corresponding value from previous model, did not change appreciably chromaticity of the optics.
* beta-beating and tunes shift with new BC model, without aby optics correction, is neglishable, indicating the longitudinal profile of quadrupole did not change from previous model
* multipoles seem small but exact dynamical aperture calculations are pending...
* wiki updating is pending...

**Comment by xresende** [comment]
DA results completed. they show that beam lifetime and dynamical acceptances did not change with new BC model. **THE MODEL IS THUS APPROVED**
