### ISSUE TITLE
Added new model (Model 13)

### ISSUE THREAD

**Issue by LuanaVilela** [lnls-ima/si-dipoles-bc#4]
Added new BC model with smaller high field gap:
si-dipoles-bc/model-13/simulation/magnetic/ 2018-10-10_bc_model13_X=-90_12mm_Z=-1000_1000mm.txt

**Comment by xresende** [comment]
integrated dipolar and quadrupolar field components are basically the same as in model-12. integrated sextupole is somewhat higher. running beam dynamical aperture calculations...

**Comment by xresende** [comment]
dynapt results show to deterioration of beam lifetime or injection efficiency.
model 13 is approved!

**Comment by xresende** [comment]
@LuanaVilela , should we update drawings of BC magnet in Sirius wiki pages?

**Comment by LuanaVilela** [comment]
The drawings have been updated!
